### ISSUE TITLE
Make next tag 0.1.0

### ISSUE THREAD

**Issue by tkelman** [sjkelly/SerialPorts.jl#8]
It looks like 0.0.3 and earlier supported Julia 0.3, but 0.0.4 and later don't. For future sanity in case an 0.3 bugfix is ever needed, would be good to get new 0.4-only releases on a separate minor package version. Thanks!

**Comment by sjkelly** [comment]
Thanks for the reminder! I've been meaning to fix it in METADATA.

**Comment by sjkelly** [comment]
Turns out it was faster to just fix the bug on 0.3. :P
