### ISSUE TITLE
SerialPort("/dev/ttyACM1", 9600) generates error on Julia 0.4.1

### ISSUE THREAD

**Issue by few** [sjkelly/SerialPorts.jl#9]
julia> versioninfo()
Julia Version 0.4.1
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

I don't know if other versions are affected.

s = SerialPort("/dev/ttyACM1", 9600)
ERROR: MethodError: `convert` has no method matching convert(::Type{SerialPorts.SerialPort}, ::ASCIIString, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::PyCall.PyObject)
This may have arisen from a call to the constructor SerialPorts.SerialPort(...),
since type constructors fall back to convert methods.
Closest candidates are:
  SerialPorts.SerialPort(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  SerialPorts.SerialPort(::ASCIIString, ::Int64, ::Int64, ::ASCIIString, ::Int64, ::Any, ::Bool, ::Bool, ::Bool, ::PyCall.PyObject)
  SerialPorts.SerialPort(::Any, ::Any)
  ...
 in call at essentials.jl:57
 in call at /home/luther/.julia/v0.4/SerialPorts/src/SerialPorts.jl:59

**Comment by sjkelly** [comment]
Thanks for the report, looks like the bug was introduced with this commit: https://github.com/sjkelly/SerialPorts.jl/commit/145ba841dca51c85c87c4343e010f09f8a556e36

**Comment by sjkelly** [comment]
This should be fixed on master. I am going to add a simple example so it is easier to catch these bugs next time. I'll get a new tag out in a couple of hours for you!
